import Ember from 'ember';

export default Ember.Route.extend({
  model() {
    return [
      {
        title: 'Herberg Macharius - 14/05',
        type: 'boardgamenight',
        date: new Date(2017, 5, 11, 19, 42, 0),
        text: '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque et dictum leo, eu dignissim lorem. In hac habitasse platea dictumst. Nulla lobortis blandit erat, id fermentum erat tempus at. Cras massa neque, consectetur sed sodales id, hendrerit eget enim. Nam molestie sagittis tellus, ut tincidunt purus dapibus sit amet. Fusce auctor leo eu mi tristique, consectetur elementum justo volutpat. Cras feugiat, nunc non luctus posuere, tellus diam tincidunt sem, at pulvinar nisl turpis eu orci. Nulla est risus, euismod ut vulputate at, laoreet eu purus. Maecenas consequat nunc lectus, in viverra magna posuere et. Proin condimentum purus vitae sapien condimentum elementum. Nam dolor quam, gravida ut ultricies at, rutrum vitae ipsum.</p><p>Sed sed eros erat. Vivamus placerat imperdiet diam et dignissim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer risus justo, feugiat non metus nec, molestie viverra arcu. Vestibulum massa ipsum, pellentesque id condimentum in, ultricies sed enim. Vivamus est felis, mattis faucibus tincidunt in, consectetur non lectus. In egestas sapien eu nulla varius mattis quis et ipsum.</p><p>Vivamus pretium sodales orci non maximus. Phasellus aliquet scelerisque turpis eget scelerisque. In vel maximus mauris. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum vitae sollicitudin mauris, non sollicitudin sapien. Nunc non tortor a erat mattis condimentum. Quisque eget tincidunt diam. Integer condimentum, enim et aliquam faucibus, neque nulla congue dui, pellentesque bibendum lectus justo quis nisl. Nullam congue, ligula et porttitor efficitur, lectus risus sollicitudin lacus, a auctor arcu orci non eros.</p><p>Nam commodo iaculis porttitor. Nullam sed tellus quis est porttitor sagittis nec eu ipsum. Duis sed nibh sagittis, facilisis erat vitae, blandit sapien. Praesent ac semper neque. Phasellus gravida, libero eu euismod hendrerit, ligula eros egestas turpis, non ullamcorper massa urna non leo. Vestibulum pretium dapibus faucibus. Etiam porttitor finibus lacus ac vehicula. Morbi dignissim eget dui congue mollis. Curabitur rhoncus est at condimentum lacinia. Morbi nec nibh tincidunt, feugiat est non, maximus nunc. Praesent scelerisque fringilla felis quis suscipit. Sed aliquam varius diam non tempor. Nam quis nibh ac felis venenatis semper. In eu malesuada lacus. Sed pharetra non lorem ac tincidunt. Sed ultrices tortor a dui sollicitudin dignissim.</p><p>Sed at nisi sed mi mattis dignissim. Proin vel dignissim velit. Quisque posuere convallis rutrum. Duis sed semper est. Aenean sollicitudin metus non urna venenatis dictum eget et massa. Praesent diam risus, dictum eget lobortis et, lacinia vitae tortor. Vestibulum at lorem id odio scelerisque luctus.</p>',
        tags: [ 'news', 'weather' ]
      },
          {
        title: 'Website News!',
        type: 'website',
        date: new Date(2017, 5, 10, 19, 42, 0),
        text: '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque et dictum leo, eu dignissim lorem. In hac habitasse platea dictumst. Nulla lobortis blandit erat, id fermentum erat tempus at. Cras massa neque, consectetur sed sodales id, hendrerit eget enim. Nam molestie sagittis tellus, ut tincidunt purus dapibus sit amet. Fusce auctor leo eu mi tristique, consectetur elementum justo volutpat. Cras feugiat, nunc non luctus posuere, tellus diam tincidunt sem, at pulvinar nisl turpis eu orci. Nulla est risus, euismod ut vulputate at, laoreet eu purus. Maecenas consequat nunc lectus, in viverra magna posuere et. Proin condimentum purus vitae sapien condimentum elementum. Nam dolor quam, gravida ut ultricies at, rutrum vitae ipsum.</p><p>Sed sed eros erat. Vivamus placerat imperdiet diam et dignissim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer risus justo, feugiat non metus nec, molestie viverra arcu. Vestibulum massa ipsum, pellentesque id condimentum in, ultricies sed enim. Vivamus est felis, mattis faucibus tincidunt in, consectetur non lectus. In egestas sapien eu nulla varius mattis quis et ipsum.</p><p>Vivamus pretium sodales orci non maximus. Phasellus aliquet scelerisque turpis eget scelerisque. In vel maximus mauris. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum vitae sollicitudin mauris, non sollicitudin sapien. Nunc non tortor a erat mattis condimentum. Quisque eget tincidunt diam. Integer condimentum, enim et aliquam faucibus, neque nulla congue dui, pellentesque bibendum lectus justo quis nisl. Nullam congue, ligula et porttitor efficitur, lectus risus sollicitudin lacus, a auctor arcu orci non eros.</p><p>Nam commodo iaculis porttitor. Nullam sed tellus quis est porttitor sagittis nec eu ipsum. Duis sed nibh sagittis, facilisis erat vitae, blandit sapien. Praesent ac semper neque. Phasellus gravida, libero eu euismod hendrerit, ligula eros egestas turpis, non ullamcorper massa urna non leo. Vestibulum pretium dapibus faucibus. Etiam porttitor finibus lacus ac vehicula. Morbi dignissim eget dui congue mollis. Curabitur rhoncus est at condimentum lacinia. Morbi nec nibh tincidunt, feugiat est non, maximus nunc. Praesent scelerisque fringilla felis quis suscipit. Sed aliquam varius diam non tempor. Nam quis nibh ac felis venenatis semper. In eu malesuada lacus. Sed pharetra non lorem ac tincidunt. Sed ultrices tortor a dui sollicitudin dignissim.</p><p>Sed at nisi sed mi mattis dignissim. Proin vel dignissim velit. Quisque posuere convallis rutrum. Duis sed semper est. Aenean sollicitudin metus non urna venenatis dictum eget et massa. Praesent diam risus, dictum eget lobortis et, lacinia vitae tortor. Vestibulum at lorem id odio scelerisque luctus.</p>',
        tags: [ 'boardgame' ]
      },
      {
        title: 'News Bulletin',
        type: 'news',
        date: new Date(2017, 5, 9, 19, 42, 0),
        text: '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque et dictum leo, eu dignissim lorem. In hac habitasse platea dictumst. Nulla lobortis blandit erat, id fermentum erat tempus at. Cras massa neque, consectetur sed sodales id, hendrerit eget enim. Nam molestie sagittis tellus, ut tincidunt purus dapibus sit amet. Fusce auctor leo eu mi tristique, consectetur elementum justo volutpat. Cras feugiat, nunc non luctus posuere, tellus diam tincidunt sem, at pulvinar nisl turpis eu orci. Nulla est risus, euismod ut vulputate at, laoreet eu purus. Maecenas consequat nunc lectus, in viverra magna posuere et. Proin condimentum purus vitae sapien condimentum elementum. Nam dolor quam, gravida ut ultricies at, rutrum vitae ipsum.</p><p>Sed sed eros erat. Vivamus placerat imperdiet diam et dignissim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer risus justo, feugiat non metus nec, molestie viverra arcu. Vestibulum massa ipsum, pellentesque id condimentum in, ultricies sed enim. Vivamus est felis, mattis faucibus tincidunt in, consectetur non lectus. In egestas sapien eu nulla varius mattis quis et ipsum.</p><p>Vivamus pretium sodales orci non maximus. Phasellus aliquet scelerisque turpis eget scelerisque. In vel maximus mauris. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum vitae sollicitudin mauris, non sollicitudin sapien. Nunc non tortor a erat mattis condimentum. Quisque eget tincidunt diam. Integer condimentum, enim et aliquam faucibus, neque nulla congue dui, pellentesque bibendum lectus justo quis nisl. Nullam congue, ligula et porttitor efficitur, lectus risus sollicitudin lacus, a auctor arcu orci non eros.</p><p>Nam commodo iaculis porttitor. Nullam sed tellus quis est porttitor sagittis nec eu ipsum. Duis sed nibh sagittis, facilisis erat vitae, blandit sapien. Praesent ac semper neque. Phasellus gravida, libero eu euismod hendrerit, ligula eros egestas turpis, non ullamcorper massa urna non leo. Vestibulum pretium dapibus faucibus. Etiam porttitor finibus lacus ac vehicula. Morbi dignissim eget dui congue mollis. Curabitur rhoncus est at condimentum lacinia. Morbi nec nibh tincidunt, feugiat est non, maximus nunc. Praesent scelerisque fringilla felis quis suscipit. Sed aliquam varius diam non tempor. Nam quis nibh ac felis venenatis semper. In eu malesuada lacus. Sed pharetra non lorem ac tincidunt. Sed ultrices tortor a dui sollicitudin dignissim.</p><p>Sed at nisi sed mi mattis dignissim. Proin vel dignissim velit. Quisque posuere convallis rutrum. Duis sed semper est. Aenean sollicitudin metus non urna venenatis dictum eget et massa. Praesent diam risus, dictum eget lobortis et, lacinia vitae tortor. Vestibulum at lorem id odio scelerisque luctus.</p>',
        tags: [ 'website', 'functionality' ]
      }
    ]
  }
});
